# close button
X = "X"
":" = ":"
confirm = "Confirm"
cancel = "Cancel"
return = "Return"
next = "Next"
previous = "Previous"

[warning]
title = "Warning!"
content = "TODO"

[main_menu]
title = "R"
new_game = "New Game"
load = "Load"
settings = "Settings"
credits = "Credits"
exit = "Exit"

[save_menu]
title = "Save"
save = "Save"

[load_menu]
title = "Load"
search_placeholder = "Search..."
name = "Name"
chapter = "Chapter"
elapsed_time = "Elapsed Time"

[settings_menu]
title = "Settings"
language = "Language"
resolution = "Resolution"
fullscreen = "Fullscreen"

allow_furry = "Allow Furry Characters"
exp_for_active_minion = "Only Characters \nWho Participate in Missions \nGain Experience Points"
iron_man = "Iron Man Mode"
difficulty = "Difficulty"
easy = "Easy"
normal = "Normal"
hard = "Hard"
custom = "Custom"
small = "Small"
large = "Large"
retrain = "Allow Retrain Characters"
enemy_critical_success = "Allow Enemy Achieve Critical Success"
revive_after_battle = "Revive Characters after Battle"
remove_debuff_after_battle = "Remove Debuffs after Battle"
enemy_squad_size = "Enemies Squad Size"
enemy_skill_set = "Available Skills for Enemies"
env_effect = "Environmental Impact Level"

[credits]
title = "Credits"
content = "TODO"

[character_creation]
title = "Character Creation"

[character]
first_name = "First Name"
last_name = "Last Name"
race = "Race"
sex = "Sex"
class = "Class"

[skills.sword_slash]
name = "Attack"
description = "A powerful sword attack that deals damage to a *single* target."

[skills.charge]
name = "Charge"
description = "A powerful sword attack that deals damage to a *single* target."
