[[unit_types]]
name = ""
skills = []

[[unit_types]]
name = "Æþelræd_lv1"
skills = ["sword_pierce"]

[[unit_types]]
name = "Ælfrēd_lv1"
skills = ["sword_pierce"]

[[unit_types]]
name = "Burhræd_lv1"
skills = ["sword_pierce"]

[[unit_types]]
name = "saxon_soldier_lv1"
skills = ["sword_pierce"]

[[unit_types]]
name = "saxon_archer_lv1"
skills = ["bow_shot"]

[[unit_types]]
name = "saxon_priest_lv1"
skills = []

[[unit_types]]
name = "Ívarr_lv1"
skills = []

[[unit_types]]
name = "Hálfdan_lv1"
skills = []

[[unit_types]]
name = "Ubbi_lv1"
skills = []

[[unit_types]]
name = "Bagsecg_lv1"
skills = []

[[unit_types]]
name = "Guðrum_lv1"
skills = []

[[unit_types]]
name = "norse_fighter_lv1"
skills = []

[[unit_types]]
name = "norse_archer_lv1"
skills = []
