function_signatures = [
    "check_item_quantity(item_id: string, operator: string, value: int) -> boolean",
    "modify_item_quantity(item_id: string, operation: string, value: int) -> boolean",
    "modify_character(character_id: string, operation: string) -> boolean",
    "always_true() -> boolean",
]

[nodes.battle_1]
type = "battle"

[nodes.battle_1.pos]
x = 500.39996337890625
y = 250.4000244140625

[[nodes.battle_1.outcomes]]
result = "victory"
next_node = "dialogue_5"

[[nodes.battle_1.outcomes.actions]]
function = "modify_item_quantity"

[nodes.battle_1.outcomes.actions.params]
item_id = "map_001"
operation = "+"
value = 2

[[nodes.battle_1.outcomes]]
result = "defeat"
next_node = "game_over"

[[nodes.battle_1.outcomes]]
result = "escape"
next_node = "dialogue_6"

[[nodes.battle_1.outcomes.conditions]]
function = "check_item_quantity"

[nodes.battle_1.outcomes.conditions.params]
item_id = "escape_orb"
operator = "="
value = 1

[[nodes.battle_1.outcomes.actions]]
function = "modify_item_quantity"

[nodes.battle_1.outcomes.actions.params]
item_id = "escape_orb"
operation = "-"
value = 1

[nodes.condition_1]
type = "condition"

[nodes.condition_1.pos]
x = 843.5999755859375
y = 164.0

[[nodes.condition_1.conditions]]
function = "check_item_quantity"
next_node = "dialogue_7"

[nodes.condition_1.conditions.params]
item_id = "key_001"
operator = ">"
value = 0

[[nodes.condition_1.conditions]]
function = "check_item_quantity"
next_node = "dialogue_8"

[nodes.condition_1.conditions.params]
item_id = "map_001"
operator = ">="
value = 2

[[nodes.condition_1.conditions]]
function = "always_true"
next_node = "dialogue_9"

[nodes.condition_1.conditions.params]

[nodes.dialogue_1]
type = "dialogue"
next_node = "option_1"

[nodes.dialogue_1.pos]
x = 81.60000610351563
y = 165.59999084472656

[[nodes.dialogue_1.dialogues]]
speaker = "NPC_001"
text = "歡迎來到村莊！這是一把鑰匙，拿去吧！"

[[nodes.dialogue_1.dialogues]]
speaker = "Player"
text = "謝謝，我會好好使用它。"

[[nodes.dialogue_1.actions]]
function = "modify_item_quantity"

[nodes.dialogue_1.actions.params]
item_id = "key_001"
operation = "+"
value = 1

[nodes.dialogue_2]
type = "dialogue"
next_node = "battle_1"

[nodes.dialogue_2.pos]
x = 350.3999938964844
y = 233.5999755859375

[[nodes.dialogue_2.dialogues]]
speaker = "NPC_001"
text = "太好了！戰士艾倫將加入你的隊伍，一起擊敗怪獸吧！"

[[nodes.dialogue_2.actions]]
function = "modify_character"

[nodes.dialogue_2.actions.params]
character_id = "char_001"
operation = "+"

[nodes.dialogue_3]
type = "dialogue"
next_node = "end"

[nodes.dialogue_3.pos]
x = 354.79998779296875
y = 317.6000061035156

[[nodes.dialogue_3.dialogues]]
speaker = "NPC_001"
text = "沒關係，也許下次你會改變主意。"

[nodes.dialogue_4]
type = "dialogue"
next_node = "option_1"

[nodes.dialogue_4.pos]
x = 322.79998779296875
y = 426.39996337890625

[[nodes.dialogue_4.dialogues]]
speaker = "NPC_001"
text = "這個村莊正面臨怪獸的威脅，我們需要勇者幫忙！"

[nodes.dialogue_5]
type = "dialogue"
next_node = "end"

[nodes.dialogue_5.pos]
x = 704.7999267578125
y = 332.8000183105469

[[nodes.dialogue_5.dialogues]]
speaker = "NPC_001"
text = "你擊敗了怪獸！村莊安全了！"

[nodes.dialogue_6]
type = "dialogue"
next_node = "option_2"

[nodes.dialogue_6.pos]
x = 624.3998413085938
y = 180.8000030517578

[[nodes.dialogue_6.dialogues]]
speaker = "Player"
text = "我成功逃脫了戰鬥，但得小心行事。"

[nodes.dialogue_7]
type = "dialogue"
next_node = "end"

[nodes.dialogue_7.pos]
x = 1000.0
y = 44.0

[[nodes.dialogue_7.dialogues]]
speaker = "NPC_002"
text = "你有鑰匙！可以進入寶藏房間。"

[nodes.dialogue_8]
type = "dialogue"
next_node = "end"

[nodes.dialogue_8.pos]
x = 1006.4000244140625
y = 137.59999084472656

[[nodes.dialogue_8.dialogues]]
speaker = "NPC_002"
text = "你有足夠的地圖！可以找到隱藏路徑。"

[nodes.dialogue_9]
type = "dialogue"
next_node = "end"

[nodes.dialogue_9.pos]
x = 1005.60009765625
y = 214.39999389648438

[[nodes.dialogue_9.dialogues]]
speaker = "NPC_002"
text = "你需要鑰匙或足夠的地圖才能繼續。"

[nodes.end]
type = "end"

[nodes.end.pos]
x = 1216.400146484375
y = 234.39999389648438

[nodes.game_over]
type = "dialogue"
next_node = "end"

[nodes.game_over.pos]
x = 670.0
y = 448.7999572753906

[[nodes.game_over.dialogues]]
speaker = "System"
text = "遊戲結束！你被擊敗了。"

[nodes.option_1]
type = "option"

[nodes.option_1.pos]
x = 180.40000915527344
y = 279.1999816894531

[[nodes.option_1.options]]
text = "接受任務"
next_node = "dialogue_2"

[[nodes.option_1.options]]
text = "拒絕任務"
next_node = "dialogue_3"

[[nodes.option_1.options]]
text = "詢問更多資訊"
next_node = "dialogue_4"

[[nodes.option_1.options.conditions]]
function = "check_item_quantity"

[nodes.option_1.options.conditions.params]
item_id = "map_001"
operator = ">"
value = 0

[[nodes.option_1.options.actions]]
function = "modify_item_quantity"

[nodes.option_1.options.actions.params]
item_id = "map_001"
operation = "-"
value = 1

[nodes.option_2]
type = "option"

[nodes.option_2.pos]
x = 700.7999877929688
y = 109.60002136230469

[[nodes.option_2.options]]
text = "繼續探索"
next_node = "condition_1"

[[nodes.option_2.options]]
text = "返回村莊"
next_node = "dialogue_1"

[[nodes.option_2.options.conditions]]
function = "check_item_quantity"

[nodes.option_2.options.conditions.params]
item_id = "village_pass"
operator = ">="
value = 1

[[nodes.option_2.options.actions]]
function = "modify_character"

[nodes.option_2.options.actions.params]
character_id = "char_001"
operation = "-"
